import { useEffect, useState } from 'react';
import { getAvailability, saveAvailability, addDayOff, removeDayOff } from '../../lib/workspaceApi.js';
import { useDocumentMeta } from '../../lib/useDocumentMeta.js';
import { useResource, PageHead, LoadState, dateLabel } from './shared.jsx';
const DAYS = ['Sun', 'Mon', 'Tue', 'Wed', 'Thu', 'Fri', 'Sat'];
const DEFAULTS = [1, 2, 3, 4, 5].map(weekday => ({ weekday, startHour: 9, endHour: 17 }));
const hour = h => `${String(h % 24).padStart(2, '0')}:00`;
export default function AvailabilityPage() {
  useDocumentMeta({ title: 'Availability', description: 'Your weekly booking hours on Servix.' });
  const r = useResource(getAvailability); const [week, setWeek] = useState(null); const [saving, setSaving] = useState(false); const [message, setMessage] = useState(null); const [dayOff, setDayOff] = useState({ date: '', reason: '' }); const [busyOff, setBusyOff] = useState(false);
  useEffect(() => { if (r.data) { const rules = r.data.usingDefaults ? DEFAULTS : r.data.rules; setWeek([0, 1, 2, 3, 4, 5, 6].map(d => { const rule = rules.find(x => x.weekday === d); return { weekday: d, on: Boolean(rule), startHour: rule?.startHour ?? 9, endHour: rule?.endHour ?? 17 }; })); } }, [r.data]);
  async function save() { const rules = week.filter(d => d.on).map(({ weekday, startHour, endHour }) => ({ weekday, startHour, endHour })); if (rules.some(x => x.endHour <= x.startHour)) { setMessage({ kind: 'warn', text: 'End time must be after start time on every working day.' }); return; } setSaving(true); setMessage(null); try { await saveAvailability(rules); setMessage({ kind: 'ok', text: rules.length ? 'Your weekly hours are saved. Customers can only book free one-hour slots inside these hours.' : 'You have no working days set, so Servix is using the default Monday–Friday 09:00–17:00 hours.' }); r.setData(d => ({ ...d, usingDefaults: rules.length === 0, rules })); } catch (e) { setMessage({ kind: 'warn', text: e.message }); } finally { setSaving(false); } }
  async function addOff(e) { e.preventDefault(); if (!dayOff.date) return; setBusyOff(true); setMessage(null); try { const row = await addDayOff(dayOff.date, dayOff.reason.trim() || undefined); r.setData(d => ({ ...d, exceptions: [...d.exceptions.filter(x => x.date !== row.date), row].sort((a, b) => a.date.localeCompare(b.date)) })); setDayOff({ date: '', reason: '' }); } catch (err) { setMessage({ kind: 'warn', text: err.message }); } finally { setBusyOff(false); } }
  async function removeOff(id) { try { await removeDayOff(id); r.setData(d => ({ ...d, exceptions: d.exceptions.filter(x => x.id !== id) })); } catch (err) { setMessage({ kind: 'warn', text: err.message }); } }
  return <><PageHead title="Availability" description="Set the hours customers can book you. Existing bookings are never moved by changing these settings." /><LoadState skeleton="form" label="Loading your availability…" resource={r}>{() => week && <>
    {message && <div className="ws-alert" role={message.kind === 'warn' ? 'alert' : 'status'} style={message.kind === 'ok' ? { background: '#eef6e8', borderColor: '#cfe2c2' } : undefined}>{message.text}</div>}
    <div className="ws-two-col">
      <section className="ws-panel"><h2>Weekly hours</h2>{r.data.usingDefaults && <p className="ws-muted" style={{ marginBottom: 14 }}>You haven't set custom hours yet, so the Servix default (Monday–Friday, 09:00–17:00) applies.</p>}
        {week && <div className="ws-week">{week.map((d, i) => <div className={`ws-week-row ${d.on ? '' : 'is-off'}`} key={d.weekday}><label><input type="checkbox" checked={d.on} onChange={e => setWeek(w => w.map((x, j) => j === i ? { ...x, on: e.target.checked } : x))} aria-label={`${DAYS[d.weekday]} working day`} /> {DAYS[d.weekday]}</label><select value={d.startHour} disabled={!d.on} aria-label={`${DAYS[d.weekday]} start`} onChange={e => setWeek(w => w.map((x, j) => j === i ? { ...x, startHour: Number(e.target.value) } : x))}>{Array.from({ length: 24 }, (_, h) => <option key={h} value={h}>{hour(h)}</option>)}</select><select value={d.endHour} disabled={!d.on} aria-label={`${DAYS[d.weekday]} end`} onChange={e => setWeek(w => w.map((x, j) => j === i ? { ...x, endHour: Number(e.target.value) } : x))}>{Array.from({ length: 24 }, (_, h) => h + 1).map(h => <option key={h} value={h}>{hour(h)}</option>)}</select><span className="ws-muted">{d.on ? `${d.endHour - d.startHour} bookable hour${d.endHour - d.startHour === 1 ? '' : 's'}` : 'Day off'}</span></div>)}</div>}
        <div className="ws-actions" style={{ marginTop: 20 }}><button className="btn btn--primary" disabled={saving || !week} onClick={save}>{saving ? 'Saving…' : 'Save weekly hours'}</button></div>
      </section>
      <section className="ws-panel"><h2>Days off</h2><p className="ws-muted" style={{ marginBottom: 14 }}>Block specific dates — holidays, travel or a full calendar elsewhere.</p>
        <form className="ws-form" onSubmit={addOff}><label>Date<input type="date" required value={dayOff.date} min={new Date().toISOString().slice(0, 10)} onChange={e => setDayOff(v => ({ ...v, date: e.target.value }))} /></label><label>Note (optional, private)<input maxLength={120} value={dayOff.reason} placeholder="e.g. Public holiday" onChange={e => setDayOff(v => ({ ...v, reason: e.target.value }))} /></label><button className="btn btn--secondary" disabled={busyOff || !dayOff.date}>{busyOff ? 'Adding…' : 'Add day off'}</button></form>
        {r.data.exceptions.length > 0 && <ul style={{ listStyle: 'none', padding: 0, marginTop: 18 }}>{r.data.exceptions.map(x => <li className="ws-row" key={x.id}><div><h3>{dateLabel(x.date)}</h3>{x.reason && <p>{x.reason}</p>}</div><button className="ws-muted" onClick={() => removeOff(x.id)}>Remove</button></li>)}</ul>}
      </section>
    </div>
  </>}</LoadState></>;
}
