import { useState } from 'react';
import { Link } from 'react-router-dom';
import { getNotifications, markNotificationsRead } from '../../lib/workspaceApi.js';
import { useDocumentMeta } from '../../lib/useDocumentMeta.js';
import { Icon } from '../../components/ui/Icon.jsx';
import { NOTIFICATIONS_EVENT } from '../../components/dashboard/WorkspaceShell.jsx';
import { useResource, PageHead, LoadState, Empty } from './shared.jsx';
const ICONS = { booking: 'calendar', chat: 'mail', connection: 'users', payout: 'wallet', plan: 'crown', review: 'star', application: 'file', admin: 'megaphone' };
const when = v => new Date(v).toLocaleString('en-GB', { day: 'numeric', month: 'short', year: 'numeric', hour: '2-digit', minute: '2-digit' });
export default function NotificationsPage() {
  useDocumentMeta({ title: 'Notifications', description: 'Your private Servix notifications.' });
  const r = useResource(getNotifications); const [more, setMore] = useState({ items: [], before: undefined, busy: false, error: '' }); const [filter, setFilter] = useState('all'); const [busy, setBusy] = useState(false); const [error, setError] = useState('');
  const items = [...(r.data?.items ?? []), ...more.items]; const before = more.before === undefined ? r.data?.before : more.before;
  const shown = items.filter(i => filter === 'all' || (filter === 'unread' ? !i.readAt : i.type.startsWith(filter)));
  async function readAll() { setBusy(true); setError(''); try { await markNotificationsRead(); const now = new Date().toISOString(); r.setData(d => ({ ...d, unread: 0, items: d.items.map(i => ({ ...i, readAt: i.readAt || now })) })); setMore(m => ({ ...m, items: m.items.map(i => ({ ...i, readAt: i.readAt || now })) })); window.dispatchEvent(new Event(NOTIFICATIONS_EVENT)); } catch (e) { setError(e.message); } finally { setBusy(false); } }
  async function readOne(item) { if (item.readAt) return; try { await markNotificationsRead([item.id]); const now = new Date().toISOString(); const mark = list => list.map(i => i.id === item.id ? { ...i, readAt: now } : i); r.setData(d => ({ ...d, unread: Math.max(0, d.unread - 1), items: mark(d.items) })); setMore(m => ({ ...m, items: mark(m.items) })); window.dispatchEvent(new Event(NOTIFICATIONS_EVENT)); } catch { /* read state is best-effort */ } }
  async function loadMore() { setMore(m => ({ ...m, busy: true, error: '' })); try { const page = await getNotifications(before); setMore(m => ({ items: [...m.items, ...page.items], before: page.before, busy: false, error: '' })); } catch (e) { setMore(m => ({ ...m, busy: false, error: e.message })); } }
  return <><PageHead title="Notifications" description="Booking updates, messages, payouts and Servix announcements — all generated by real activity on your account.">{r.data?.unread > 0 && <button className="btn btn--secondary" disabled={busy} onClick={readAll}>{busy ? 'Updating…' : `Mark all ${r.data.unread} as read`}</button>}</PageHead>
    <LoadState skeleton="list" label="Loading notifications…" resource={r}>
      {error && <div className="ws-alert" role="alert">{error}</div>}
      <div className="ws-tabs" role="group" aria-label="Filter notifications">{[['all', 'All'], ['unread', 'Unread'], ['booking', 'Bookings'], ['chat', 'Messages'], ['connection', 'Network'], ['admin', 'Announcements']].map(([id, label]) => <button key={id} aria-pressed={filter === id} onClick={() => setFilter(id)}>{label}</button>)}</div>
      <section className="ws-panel">{!shown.length ? <Empty icon="bell" title={filter === 'all' ? 'No notifications yet' : 'Nothing here'} description={filter === 'all' ? 'When a booking changes, someone messages you or Servix shares an update, it will appear here.' : 'No notifications match this filter.'} /> :
        <ul className="ws-notif-list">{shown.map(item => <li key={item.id} className={item.readAt ? '' : 'is-unread'}><span className="ws-notif-icon"><Icon name={ICONS[item.type.split('.')[0]] || 'bell'} size={18} /></span><div><h3>{item.title}</h3><p>{item.body}</p><small>{when(item.createdAt)}{item.readAt ? '' : ' · Unread'}</small>{item.link && <Link to={item.link} onClick={() => readOne(item)}>Open →</Link>}{!item.readAt && <button className="ws-muted" style={{ marginLeft: 10, fontSize: 11 }} onClick={() => readOne(item)}>Mark read</button>}</div></li>)}</ul>}
        {before && <div className="ws-actions" style={{ justifyContent: 'center', marginTop: 16 }}><button className="btn btn--secondary" disabled={more.busy} onClick={loadMore}>{more.busy ? 'Loading…' : 'Load older notifications'}</button>{more.error && <span role="alert" className="ws-muted">{more.error}</span>}</div>}
      </section>
      <p className="ws-muted">Servix never asks for your password, card PIN or verification codes in a notification. Report anything suspicious to <Link to="/contact">support</Link>.</p>
    </LoadState></>;
}
