import { useState } from 'react';
import { Link } from 'react-router-dom';
import { getPayments } from '../../lib/workspaceApi.js';
import { formatPrice } from '../../lib/format.js';
import { useDocumentMeta } from '../../lib/useDocumentMeta.js';
import { useResource, PageHead, LoadState, Empty, dateLabel } from './shared.jsx';
export default function PaymentsPage(){
  useDocumentMeta({title:'Payments',description:'Your private Servix payment records.'});
  const r=useResource(getPayments);const [status,setStatus]=useState('all');const rows=r.data?.records??[];
  const filtered=rows.filter(p=>status==='all'||p.status===status);
  function download(){const cell=v=>'"'+String(v??'').replace(/^[=+@\-]/,"'$&").replaceAll('"','""')+'"';const csv=[['Reference','Booking','Amount','Currency','Status','Date'],...filtered.map(p=>[p.reference,p.booking.reference,p.amount,p.currency,p.status,p.createdAt])].map(row=>row.map(cell).join(',')).join('\r\n');const url=URL.createObjectURL(new Blob([csv],{type:'text/csv;charset=utf-8'}));const a=document.createElement('a');a.href=url;a.download='servix-payment-records.csv';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
  return <><PageHead title="Payments" description="A clear view of your spending, payment status and booking records."><button className="btn btn--secondary" disabled={!filtered.length} onClick={download}>Export records ↓</button></PageHead><LoadState skeleton="table" label="Loading your payments…" resource={r}>{r.data?.mode!=='live'&&<div className="ws-alert"><strong>Payment testing mode.</strong> These records may be test transactions. Do not treat them as real charges or use real card details in a sandbox checkout.</div>}<div className="ws-stat-grid"><div className="ws-stat"><span>Captured payments · NGN</span><strong>{formatPrice(rows.filter(p=>p.status==='captured'&&p.currency==='NGN').reduce((s,p)=>s+p.amount,0))}</strong><small>From the latest 100 records</small></div><div className="ws-stat"><span>Awaiting confirmation</span><strong>{rows.filter(p=>p.status==='initiated').length}</strong><small>Not confirmed charges</small></div><div className="ws-stat"><span>Refund records</span><strong>{rows.filter(p=>p.status==='refunded').length}</strong><small>Bank processing times vary</small></div><div className="ws-stat"><span>Your payment provider</span><strong style={{fontSize:22}}>Secure checkout</strong><small>Full card details are not stored here</small></div></div><section className="ws-panel"><div className="ws-row"><h2>Transaction history</h2><label className="ws-muted">Status <select value={status} onChange={e=>setStatus(e.target.value)} aria-label="Payment status"><option value="all">All records</option>{['initiated','captured','failed','refunded'].map(v=><option key={v}>{v}</option>)}</select></label></div>{!filtered.length?<Empty title="No payment records here yet" description="When you pay for a booking, its payment status and reference will appear here." to="/dashboard/search"/>:<div className="ws-record-table"><table><thead><tr><th>BOOKING / REFERENCE</th><th>DATE</th><th>AMOUNT</th><th>STATUS</th><th>DETAILS</th></tr></thead><tbody>{filtered.map(p=><tr key={p.id}><td>{p.booking.serviceTitle}<small>{p.reference}</small></td><td>{dateLabel(p.createdAt)}</td><td>{new Intl.NumberFormat('en-NG',{style:'currency',currency:p.currency}).format(p.amount)}</td><td><span className={`ws-chip ${p.status==='initiated'?'warn':''}`}>{p.status}</span></td><td><Link to={`/bookings/${p.booking.id}`}>View booking ↗</Link></td></tr>)}</tbody></table></div>}</section><p className="ws-muted">These are payment records, not tax invoices. For a receipt, refund question or disputed charge, contact support with the reference. Never send your card details, PIN or OTP.</p></LoadState></>;
}
