import { useEffect, useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { getPlan, startPlanCheckout, verifyPlan } from '../../lib/workspaceApi.js';
import { useDocumentMeta } from '../../lib/useDocumentMeta.js';
import { formatPrice } from '../../lib/format.js';
import { useResource, PageHead, LoadState, dateLabel } from './shared.jsx';
/* Only what the platform enforces today is promised here. */
const ENFORCED = { free: ['Public professional profile', 'Up to 2 service listings', 'Client bookings, messaging and payouts', 'Basic dashboard statistics'], professional: ['Everything in Free', 'Up to 10 service listings', 'Detailed analytics: bookings, earnings, response and rating trends', 'Servix Pro badge on your public profile'], business: ['Everything in Servix Pro', 'Unlimited service listings', 'Arranged directly with Servix (contact us)'] };
export default function PlanPage() {
  useDocumentMeta({ title: 'Servix Pro plan', description: 'Your professional plan on Servix.' });
  const r = useResource(getPlan); const [params, setParams] = useSearchParams(); const [busy, setBusy] = useState(''); const [notice, setNotice] = useState(null); const reference = params.get('reference');
  useEffect(() => { if (!reference) return; let alive = true; setBusy('verify'); verifyPlan(reference).then(result => { if (!alive) return; r.setData(result.plan); setNotice(result.status === 'active' ? { kind: 'ok', text: 'Your payment was confirmed and your plan is active.' } : result.status === 'failed' ? { kind: 'warn', text: 'That payment did not complete. You have not been charged for an active plan.' } : { kind: 'warn', text: 'Your payment is still being confirmed. Refresh in a moment — the plan activates automatically once the provider confirms it.' }); }).catch(e => { if (alive) setNotice({ kind: 'warn', text: e.message }); }).finally(() => { if (alive) { setBusy(''); setParams({}, { replace: true }); } }); return () => { alive = false; }; }, [reference]);
  async function upgrade(slug) { setBusy(slug); setNotice(null); try { const { authorizationUrl } = await startPlanCheckout(slug); window.location.assign(authorizationUrl); } catch (e) { setNotice({ kind: 'warn', text: e.message }); setBusy(''); } }
  const plan = r.data;
  return <><PageHead title={plan?.current === 'free' ? 'Upgrade to Servix Pro' : `${plan?.label ?? 'Your'} plan`} description="Plans are billed monthly through the Servix payment provider. Your plan never changes your approval status or your existing bookings." /><LoadState skeleton="cards" label="Loading plans…" resource={r}>{() => <>
    {notice && <div className="ws-alert" role={notice.kind === 'warn' ? 'alert' : 'status'} style={notice.kind === 'ok' ? { background: '#eef6e8', borderColor: '#cfe2c2' } : undefined}>{notice.text}</div>}
    {busy === 'verify' && <p className="ws-muted" role="status">Confirming your payment…</p>}
    <div className="ws-stat-grid"><div className="ws-stat"><span>Current plan</span><strong style={{ fontSize: 22 }}>{plan.label}</strong><small>{plan.expiresAt ? `Active until ${dateLabel(plan.expiresAt)}` : plan.expired ? 'Your paid plan expired — you are on Free' : 'No expiry'}</small></div><div className="ws-stat"><span>Service listings</span><strong>{plan.usage.listings}{plan.limits.listings !== null && <small style={{ fontSize: 16 }}> / {plan.limits.listings}</small>}</strong><small>{plan.limits.listings === null ? 'Unlimited on this plan' : 'Drafts and published listings count'}</small></div><div className="ws-stat"><span>Analytics</span><strong style={{ fontSize: 22 }}>{plan.limits.analytics ? 'Detailed' : 'Basic'}</strong><small>{plan.limits.analytics ? 'Trends and breakdowns unlocked' : 'Upgrade for trends and breakdowns'}</small></div><div className="ws-stat"><span>Renewal</span><strong style={{ fontSize: 22 }}>Manual</strong><small>Plans do not auto-renew; you are never charged without choosing to pay</small></div></div>
    <div className="ws-plan-grid">{plan.plans.map(p => { const current = p.slug === plan.current; return <article className={`ws-plan ${current ? 'is-current' : ''}`} key={p.slug} aria-current={current ? 'true' : undefined}><span className="eyebrow">{p.slug === 'professional' ? 'Servix Pro' : p.name}</span><div className="price">{p.price ? formatPrice(p.price) : 'Free'}{p.price ? <small> / month</small> : null}</div><p className="ws-muted">{p.tagline}</p><ul>{(ENFORCED[p.slug] || []).map(f => <li key={f}>{f}</li>)}</ul>{current ? <span className="ws-chip">Your current plan</span> : p.purchasable ? <button className="btn btn--primary" disabled={Boolean(busy)} onClick={() => upgrade(p.slug)}>{busy === p.slug ? 'Opening secure checkout…' : plan.current === 'free' ? `Upgrade to Servix Pro` : `Extend by 30 days`}</button> : p.slug === 'business' ? <Link className="btn btn--secondary" to="/contact">Contact Servix</Link> : <span className="ws-muted">Included</span>}</article>; })}</div>
    {plan.subscriptions.length > 0 && <section className="ws-panel" style={{ marginTop: 22 }}><h2>Plan payment history</h2><div className="ws-record-table"><table><thead><tr><th>REFERENCE</th><th>PLAN</th><th>AMOUNT</th><th>STATUS</th><th>PERIOD</th></tr></thead><tbody>{plan.subscriptions.map(s => <tr key={s.id}><td>{s.reference}<small>{dateLabel(s.createdAt)}</small></td><td>{s.plan}</td><td>{formatPrice(s.amount)}</td><td><span className={`ws-chip ${s.status === 'active' ? '' : s.status === 'initiated' ? 'warn' : 'gray'}`}>{s.status}</span></td><td>{s.startsAt ? `${dateLabel(s.startsAt)} – ${dateLabel(s.endsAt)}` : '—'}</td></tr>)}</tbody></table></div></section>}
    <p className="ws-muted">Payments are processed by the Servix payment provider; Servix does not store your card details. Questions about a charge? <Link to="/contact">Contact support</Link> with the reference.</p>
  </>}</LoadState></>;
}
