import { useState } from 'react';
import { Link, useSearchParams } from 'react-router-dom';
import { getServices,getProfessionals } from '../../lib/httpApi.js';
import { useDocumentMeta } from '../../lib/useDocumentMeta.js';
import { useResource,PageHead,LoadState,Empty } from './shared.jsx';
import { formatPrice } from '../../lib/format.js';
export default function SearchPage(){const [params,setParams]=useSearchParams();const q=params.get('q')||'';const [input,setInput]=useState(q);const [kind,setKind]=useState('services');const [page,setPage]=useState(1);useDocumentMeta({title:'Search marketplace',description:'Find services and professionals on Servix.'});const r=useResource(()=>kind==='services'?getServices({q,page,pageSize:12}):getProfessionals({q,page,pageSize:12}),[q,kind,page]);const items=r.data?.items??[];
 return <><PageHead title="Find your next great fit" description="Search the live marketplace for services and professional expertise."/><form className="ws-input-search" role="search" onSubmit={e=>{e.preventDefault();setPage(1);setParams(input.trim()?{q:input.trim()}:{});}}><input aria-label="Marketplace search" placeholder="Try design, development or home services…" value={input} onChange={e=>setInput(e.target.value)}/><button className="btn btn--primary">Search</button></form><div className="ws-tabs">{['services','professionals'].map(k=><button key={k} aria-pressed={kind===k} onClick={()=>{setKind(k);setPage(1);}}>{k==='services'?'Services':'Professionals'}</button>)}</div><LoadState resource={r}>{!items.length?<section className="ws-panel"><Empty title="No matches yet" description="Try a different keyword or broaden your search. No sample results are substituted."/></section>:<div className="ws-card-grid">{items.map(item=><article className="ws-mini-card" key={item.id}><span className="ws-chip">{kind==='services'?'Service':'Professional'}</span><h2>{item.title||item.name}</h2>{kind==='professionals'&&<strong>{item.name}</strong>}<p>{item.shortDescription||item.location||item.category||'View details to explore this listing.'}</p>{kind==='services'&&typeof item.price==='number'&&<p>{formatPrice(item.price)} {item.priceUnit}</p>}<Link className="btn btn--secondary" to={`/${kind}/${encodeURIComponent(item.id)}`}>View {kind==='services'?'service':'profile'} ↗</Link>{kind==='professionals'&&<p style={{marginTop:15}}><Link to={`/dashboard/network?profile=${encodeURIComponent(item.id)}`}>Connect with this professional →</Link></p>}</article>)}</div>}<div className="ws-actions" style={{marginTop:24}}><button className="btn btn--secondary" disabled={page===1} onClick={()=>setPage(p=>p-1)}>Previous</button><span className="ws-muted">Page {page}</span><button className="btn btn--secondary" disabled={items.length<12} onClick={()=>setPage(p=>p+1)}>Next</button></div></LoadState></>;
}
