import { useState } from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../../lib/AuthContext.jsx';
import { updateAccount } from '../../lib/workspaceApi.js';
import { useDocumentMeta } from '../../lib/useDocumentMeta.js';
import { PageHead } from './shared.jsx';
import { PhotoUploader } from '../../components/ui/PhotoUploader.jsx';
export default function SettingsPage(){
  useDocumentMeta({title:'Account settings',description:'Manage your private Servix account.'});const {user,refreshUser}=useAuth();
  const [name,setName]=useState(user.fullName),[busy,setBusy]=useState(false),[message,setMessage]=useState(''),[error,setError]=useState('');
  const [photoMessage,setPhotoMessage]=useState(''),[photoError,setPhotoError]=useState('');
  async function savePhoto(url){setPhotoError('');setPhotoMessage('');try{await updateAccount({avatarUrl:url});await refreshUser();setPhotoMessage(url?'Your photo has been saved.':'Your photo has been removed.');}catch(e){setPhotoError(e.message);}}
  async function save(e){e.preventDefault();if(name.trim().length<2){setError('Enter at least two characters.');return;}setBusy(true);setError('');setMessage('');try{await updateAccount({fullName:name.trim()});await refreshUser();setMessage('Your account name has been saved.');}catch(e){setError(e.message);}finally{setBusy(false);}}
  return <><PageHead title="Account settings" description="Your details, preferences and account controls."/><div className="ws-two-col"><div><section className="ws-panel"><h2>Profile photo</h2><p className="ws-muted" style={{marginBottom:20}}>Shown next to your name across Servix — and on your public professional card if you have one.</p><PhotoUploader value={user.avatarUrl} name={user.fullName} onChange={savePhoto}/>{photoError&&<p role="alert" style={{marginTop:12}}>{photoError}</p>}{photoMessage&&<p role="status" style={{marginTop:12}}>{photoMessage}</p>}</section><section className="ws-panel"><h2>Personal details</h2><p className="ws-muted" style={{marginBottom:24}}>Your account name is separate from the professional profile you publish.</p><form className="ws-form" onSubmit={save}><label>Full name<input value={name} maxLength={200} minLength={2} required autoComplete="name" onChange={e=>setName(e.target.value)}/></label><label>Email address<input value={user.email} readOnly type="email"/></label><p className="ws-muted">Email changes require account ownership checks. Contact support rather than creating a duplicate account.</p>{error&&<p role="alert">{error}</p>}{message&&<p role="status">{message}</p>}<div><button className="btn btn--primary" disabled={busy}>{busy?'Saving…':'Save changes'}</button></div></form></section></div><aside><section className="ws-panel"><h2>Sign-in & security</h2><p className="ws-muted">Manage Google/GitHub connections and check your verification status.</p><div className="ws-actions" style={{marginTop:18}}><Link className="btn btn--secondary" to="/connected-sign-in">Connected accounts</Link><Link className="btn btn--secondary" to="/dashboard/verification">Security status</Link></div><p style={{marginTop:20}}><Link to="/forgot-password">Reset your password →</Link></p></section><section className="ws-panel"><h2>Privacy preferences</h2><p className="ws-muted">Optional analytics are separate from essential account and transaction messages.</p><button className="btn btn--secondary" style={{marginTop:18}} onClick={()=>window.dispatchEvent(new Event('servix:cookie-settings'))}>Cookie settings</button></section></aside></div><section className="ws-panel"><h2>Account assistance</h2><p className="ws-muted">To request account closure, deletion or a correction, contact <a href="mailto:toluenetech@gmail.com">toluenetech@gmail.com</a> from your registered address. Existing bookings and legal records may need to be resolved first. Never send passwords or recovery codes.</p></section></>;
}
