import { Link } from 'react-router-dom';
import { getSecuritySummary } from '../../lib/workspaceApi.js';
import { useWorkspace } from '../../components/dashboard/WorkspaceShell.jsx';
import { useDocumentMeta } from '../../lib/useDocumentMeta.js';
import { PageHead, LoadState, useResource } from './shared.jsx';
export default function VerificationPage(){
  useDocumentMeta({title:'Verification & security',description:'Check account verification and professional approval.'});const {overview,user}=useWorkspace();const r=useResource(getSecuritySummary);
  return <><PageHead title="Verification & security" description="Three separate checks. One more trusted experience."/><LoadState resource={r}><div className="ws-card-grid"><section className="ws-mini-card"><span className={`ws-chip ${overview?.emailVerified?'':'warn'}`}>{overview?.emailVerified?'Verified':'Action needed'}</span><h2>Email ownership</h2><p>{user.email}<br/>Your email is used for account communication and verification.</p>{!overview?.emailVerified&&<Link to="/verify-email">Verify email →</Link>}</section><section className="ws-mini-card"><span className={`ws-chip ${r.data?.method?'':'warn'}`}>{r.data?.method?'Enrolled':'Not enrolled'}</span><h2>Account security</h2><p>{r.data?.method==='passkey'?'Passkey':r.data?.method==='totp'?'Authenticator app':'No saved security method'}. {r.data?.passkeys??0} passkey credential(s) on this account.</p><Link to="/connected-sign-in">Manage sign-in providers →</Link></section><section className="ws-mini-card"><span className={`ws-chip ${overview?.canManageServices?'':'gray'}`}>{overview?.canManageServices?'Approved':overview?.applicationStatus?.replaceAll('_',' ')||'Not applied'}</span><h2>Professional approval</h2><p>Email verification and a security method do not automatically verify professional qualifications. Applications are reviewed separately.</p><Link to={overview?.canManageServices?'/dashboard/profile':'/professionals/apply'}>{overview?.canManageServices?'Open professional profile':'View application'} →</Link></section></div><section className="ws-panel" style={{marginTop:24}}><div className="ws-row"><div><h2>Keep your recovery codes safe</h2><p>{r.data?.recoveryCodesRemaining??0} unused recovery codes remain. Each works once as a backup for your saved factor.</p></div><span className="ws-chip">Private to you</span></div><p className="ws-muted">Codes and authenticator secrets are not displayed here. If you have lost your security method and recovery codes, contact support. Replacement and code regeneration are not available from this page. Never share your setup QR, key or codes.</p></section></LoadState></>;
}
