export const LEGAL_UPDATED = '28 September 2026';
export const LEGAL_VERSION = '2026-09-28';
export const LEGAL_CONTACT = 'toluenetech@gmail.com';
export const LEGAL_CONTENT = {
  privacy: {
    title: 'Privacy Policy', description: 'How Servix collects, uses and protects your information, and how to exercise your privacy rights.',
    intro: 'Your information helps us connect you with services and protect your account. This notice explains what we handle and the choices you have.',
    sections: [
      ['Who is responsible', 'Servix is operated by Toluwalase O. Samuel in Nigeria as an individual operator, not a registered company. The operator is responsible for the personal information described here. Contact toluenetech@gmail.com for privacy, access or deletion requests.'],
      ['Information you provide', 'We process your name, email, account role and status; professional applications, skills, location, service listings, portfolio images and uploads; booking schedules, notes, reviews, cancellations and dispute details; and messages sent to support. Public professional profiles, services, portfolios and reviews are visible to other visitors. Do not include passwords, identity documents, financial credentials or unnecessary sensitive information in public content or booking notes.'],
      ['Account verification and security', 'Passwords are stored as password hashes, not readable passwords. Email verification codes and reset tokens have expiry and usage checks. When security verification is enabled, we process encrypted authenticator setup secrets, passkey public keys and credential metadata, and hashed single-use recovery codes. Your device or passkey provider manages its private key and device unlock; Servix does not receive your fingerprint or face scan. Security events, session records, timestamps, device/browser information and IP addresses may be processed for protection and audit purposes. Never send support your authenticator key, QR code, password or recovery codes.'],
      ['Google and GitHub sign-in', 'Where enabled and chosen by you, we receive a provider account identifier, name and verified email to create or authenticate an account. Provider identity is separate from your enrolled Servix security method. Existing accounts are not automatically linked just because email addresses match. Our integration does not retain provider access or refresh tokens. Google and GitHub process information under their own privacy notices.'],
      ['Private messages and connections', 'Where community features are enabled, we store connection requests, acceptance or blocking status, conversation participants, message text, timestamps and read state. Conversations are limited to their booking participants or accepted connections. Blocking stops new messages; it does not erase existing history. Messages are stored on Servix servers and are not end-to-end encrypted. Necessary access by the operator or authorised support may occur for abuse reports, disputes, security or lawful requests. Do not send payment credentials, verification codes or unnecessary sensitive information in chat. Request deletion or report abuse through the contact address.'],
      ['Bookings and payments', 'We keep booking references, amounts, status, payment-provider references, refunds, dispute records and professional payout records. Payment details entered into a provider-hosted payment form are handled by that provider, rather than stored as full card details by Servix. Some payment features are still in testing; a test checkout is not a live charge or a guarantee of a real payout.'],
      ['Why we use information', 'We use account and booking information to take steps you request and perform our service agreement; security and limited operational records for legitimate interests in preventing fraud, resolving disputes and maintaining a reliable service; and records required to meet legal obligations. We seek consent for optional analytics and performance measurement. Where consent is the basis, you can withdraw it without affecting earlier lawful use. We do not treat agreement to the Terms as blanket consent for unrelated processing.'],
      ['Who receives information', 'Relevant booking information is shared with the customer or professional involved, and authorised support staff can review records needed to help you. Service providers include Vercel for website hosting and optional measurement, Railway for API hosting, Neon for the database, Cloudflare R2 for uploads, Brevo for transactional email, and Paystack where its payment integration is used. Google/GitHub receive information when you choose their sign-in options. We may disclose necessary information to comply with law, respond to lawful requests, protect people or handle a dispute. We do not sell personal information or use it for cross-site advertising.'],
      ['International processing', 'Our hosting and service providers may process information outside Nigeria, including the United States; the current database is hosted in the US. International transfers must have an applicable legal basis and appropriate safeguards under the Nigeria Data Protection Act 2023. Contact us for information about the arrangements applicable to your data. This notice does not represent that a particular provider certification or regulatory approval has been obtained.'],
      ['Cookies and optional measurement', 'Essential cookies support sign-in, restricted verification sessions and provider sign-in. A browser-storage preference remembers your measurement choice. Optional website analytics and performance measurement are off until you allow them, and are limited to public pages. We remove query strings and fragments from measurement URLs and exclude authentication and private account routes. See the Cookie Policy for names, purposes and controls.'],
      ['Retention and deletion', 'We keep account/profile information while needed to provide your account, and booking, payment, support and security records as needed for the relevant transaction, dispute, legal obligation or protection against abuse. Token expiry prevents its use; it does not mean every related database record is immediately deleted. Some deletion and retention work is handled manually, and backups may retain copies until replaced under the hosting provider’s backup cycle. Request account closure or deletion by email; we will assess what can be removed and explain any lawful reason to retain particular records. We do not promise instant deletion from every system.'],
      ['Your choices and rights', 'Subject to applicable law, you can request access, correction, deletion, restriction or portability of your information, object to processing based on legitimate interests, and withdraw optional consent. Email toluenetech@gmail.com, preferably from your account address. We may request proportionate proof of identity, but will not ask for a password, OTP or recovery code. We will respond within applicable legal time limits and explain relevant exceptions. You may complain to the Nigeria Data Protection Commission at ndpc.gov.ng; contacting us first is welcome but not a condition of exercising that right.'],
      ['Children and safety', 'Servix accounts and bookings are intended for people aged 18 or over. We do not knowingly offer accounts to children. Contact us if a child’s information has been submitted. Technical and organisational safeguards reduce risk but cannot guarantee absolute security; report suspected account compromise promptly.'],
      ['Changes to this notice', 'We will update this notice when our practices change and show the updated date. Material changes will be brought to your attention through the website or an appropriate account communication, and new consent will be requested where required.'],
    ],
  },
  terms: {
    title: 'Terms of Service', description: 'The rules for accounts, professional services, bookings, payments and disputes on Servix.',
    intro: 'Please read these terms before creating an account or booking a service. They explain what you can expect from Servix and what we ask of you.',
    sections: [
      ['Operator and agreement', 'Servix is operated by Toluwalase O. Samuel in Nigeria as an individual operator, not a registered company. Contact toluenetech@gmail.com. These terms govern your use of the platform. By creating an account or requesting a service through Servix, you agree to these terms. The Privacy Policy explains data handling separately; optional measurement consent is not required to use the platform.'],
      ['Eligibility and accounts', 'You must be at least 18 and able to enter a binding agreement. Provide accurate information and use only accounts you are authorised to access. Keep your password, email access, authenticator/passkey and recovery codes secure. Complete the verification steps required by the app. Report suspected compromise promptly. Recovery codes are available to enrolled users, not only administrators, and each can be used once.'],
      ['What Servix provides', 'Servix helps customers discover independent professionals, request bookings and manage related records. Unless clearly stated otherwise for a particular service, the professional—not Servix—performs the booked work. Listings, ratings or verification labels do not guarantee the quality, safety, licensing or suitability of a professional. Check qualifications appropriate to your work. Nothing here removes Servix’s responsibility for its own services or obligations imposed by law.'],
      ['Bookings and professional responsibilities', 'Review the scope, schedule, location requirements, price, fees and cancellation conditions before booking. A submitted or paid request is not by itself professional acceptance; follow the status in your account. Professionals must describe their services honestly, hold required permissions and qualifications, honour accepted work, protect customer information and communicate changes promptly. Customers must provide accurate instructions and reasonable access and must not request unlawful or unsafe work.'],
      ['Prices, fees and payment testing', 'Prices and any applicable platform fees are those disclosed for the transaction, generally in Nigerian naira unless stated otherwise. Ask support before proceeding if a fee or condition is unclear. Use only the payment flow provided for the booking. Payment and payout integrations may be in test mode: test transactions are not real payments or guaranteed transfers. Do not enter real payment details in a test checkout. We do not describe held booking balances as a bank deposit or regulated escrow product.'],
      ['Cancellations, refunds and disputes', 'A booking awaiting payment has no captured payment to refund. A customer cancellation before professional acceptance is eligible for a full refund of the captured amount. After acceptance but before work begins, the applicable pre-work cancellation policy determines the refund; ask support before booking if that policy is not clear. Professional cancellation or decline is eligible for a full refund of the captured amount. Once work has begun or is marked delivered, use the dispute process rather than assuming an automatic customer cancellation. Contact support promptly with the booking reference and relevant evidence. Recording or initiating a refund is not confirmation that it has reached your bank; provider processing times apply. Mandatory consumer rights take precedence.'],
      ['Completion and payouts', 'Review work and raise genuine problems promptly through your booking. Confirmation, dispute resolution and any completion rules applicable to the booking determine payment release and professional payouts. A payout notification does not guarantee immediate bank receipt. We may hold or review transactions where needed to investigate a dispute, suspected fraud or a legal requirement.'],
      ['Acceptable use and content', 'Do not commit fraud, impersonate others, harass people, post unlawful or discriminatory material, upload malicious files, infringe intellectual property, scrape private information or attempt to bypass security. Only upload material you have permission to use. You retain ownership of your content and grant Servix a non-exclusive permission to host, display and process it as needed to operate the platform and fulfil your requests. Do not publish other people’s private information without a lawful basis.'],
      ['Availability, suspension and closure', 'Features may be limited, changed or temporarily unavailable. We may restrict an account where reasonably necessary for security, unlawful activity, misuse or unresolved obligations, and provide an explanation and review route where lawful and practical. Email support to request review or account closure. Closure does not cancel an existing payment, dispute or legal obligation; relevant records may be retained as explained in the Privacy Policy.'],
      ['Responsibility and your legal rights', 'Use reasonable care when choosing a professional and agreeing the work. We do not promise uninterrupted access or a particular result from an independent professional. Liability is determined by applicable law; these terms do not exclude fraud, wilful misconduct or any duty or liability that cannot lawfully be excluded. They do not waive statutory consumer remedies or privacy rights.'],
      ['Complaints and governing law', 'Email toluenetech@gmail.com with the issue and booking reference, if any, so we can try to resolve it. Nigerian law governs these terms, subject to mandatory protections that apply to you. You retain the right to approach a competent court or relevant regulator; there is no compulsory private arbitration or waiver of that right in these terms.'],
      ['Updates', 'The date above identifies this version. Material changes will be notified through the platform or an appropriate account communication. Changes are not intended to retrospectively remove accrued rights or change an already agreed booking price. Contact us if you do not understand or accept a proposed change.'],
    ],
  },
  cookies: {
    title: 'Cookie Policy', description: 'Essential sign-in cookies, optional measurement and how to manage your Servix privacy preferences.',
    intro: 'You can use Servix without optional analytics. Essential storage keeps sign-in and verification working; optional measurement runs only if you choose to allow it.',
    sections: [
      ['Cookies and similar storage', 'Cookies are small values stored by your browser and sent to the relevant website. Local storage stays in the browser until cleared or replaced. This policy covers both. Servix is operated by Toluwalase O. Samuel; questions can be sent to toluenetech@gmail.com.'],
      ['Essential session cookie: servix_refresh', 'Used by the Servix API to maintain and renew your signed-in session. It is HttpOnly and Secure in production, with SameSite=Lax, and scoped to the authentication path. Its expiry follows the server session setting (30 days by default) and is renewed on successful refresh. Signing out clears the cookie in that browser and revokes the relevant session. Blocking it prevents persistent sign-in.'],
      ['Essential verification cookie: servix_security', 'Used to bind your browser to a restricted email/authenticator/passkey verification flow. It expires after 15 minutes and is cleared when the flow completes or is cancelled. This cookie is not a full signed-in session.'],
      ['Essential provider cookies', 'servix_oauth_google and servix_oauth_github bind Google/GitHub sign-in attempts to your browser where those options are enabled. They last up to 10 minutes and are cleared during the callback. Provider websites may set their own cookies under their own policies when you visit them.'],
      ['Preference storage: servix_cookie_preferences', 'A first-party local-storage record remembers whether you chose optional measurement, the policy version and the time of your choice. We ask again after 180 days or when this version changes. It is not used for advertising. Browser/device choices are separate; clearing site storage removes the saved choice.'],
      ['Optional analytics and performance', 'If you choose “Allow optional”, Vercel Web Analytics and Speed Insights measure public-page use and performance, including page paths, browser/device characteristics and timing information. These products are designed to work without advertising cookies; optional measurement still involves data processing. We do not load their scripts before consent. Authentication, booking, admin and workspace pages are excluded, and query strings and fragments are removed from measurement URLs. There are no advertising cookies configured by this site. Necessary hosting/security logs are separate from optional measurement.'],
      ['Change your choice', 'Use Cookie settings in the footer or the button on this page at any time. “Essential only” declines or withdraws optional measurement without blocking account access. Withdrawing an existing allowance reloads the page to stop already-loaded measurement scripts; save unfinished work first. Browser settings can also delete or block cookies, but blocking essential cookies may break sign-in. If preference storage is unavailable, optional measurement remains off.'],
      ['More information', 'See the Privacy Policy for service providers, international processing, retention and your rights. Vercel’s product privacy documentation explains its analytics and performance systems. Provider policies do not replace the choices offered here.'],
    ],
  },
};
